#!/usr/anaconda2/bin/python
# -*- coding: utf-8 -*-
################################# Fota3 Info #################################################
allFota3DeviceTable = ['devicenew201407','devicenew201408','devicenew201409','devicenew201410','devicenew201411','devicenew201412','devicenew201501','devicenew201502','devicenew201503','devicenew201504','devicenew201505','devicenew201506','devicenew201507','devicenew201508','devicenew201510','devicenew201511','devicenew201512','devicenew201601','devicenew201602','devicenew201603','devicenew201604','devicenew201605','devicenew201606','devicenew201607','devicenew201608','devicenew201609','devicenew201610','devicenew201611','devicenew201612','devicenew201701','devicenew201702','devicenew201703','devicenew201704','devicenew201705','devicenew201706','devicenew201707','devicenew201708','devicenew201709','devicenew201710','devicenew201711','devicenew201712','devicenewother']
#allFota3DeviceTable = ['devicenew201702']
allFota3RegionTable = ['region']
#allFota3RegionTable = []

v3DeviceNeedFields ="*,'0' as maingid,'0' as secondgid,'0' as secondOperator,'0' as networkType,'0' as CO1,'0' as CO2,'0' as CO3,'0' as CO4,'0' as CO5,'0' as CO6,'0' as CO7,'0' as CO8,'0' as CO9,'0' as CO10,'0' as CO11,'0' as CO12,'3.0' as data_version"
fota3Schema = {u'fields': [{u'name': u'APNType', u'type': [u'string', u'null']},
					 {u'name': u'CO1', u'type': u'string'},
					 {u'name': u'CO10', u'type': u'string'},
					 {u'name': u'CO11', u'type': u'string'},
					 {u'name': u'CO12', u'type': u'string'},
					 {u'name': u'CO2', u'type': u'string'},
					 {u'name': u'CO3', u'type': u'string'},
					 {u'name': u'CO4', u'type': u'string'},
					 {u'name': u'CO5', u'type': u'string'},
					 {u'name': u'CO6', u'type': u'string'},
					 {u'name': u'CO7', u'type': u'string'},
					 {u'name': u'CO8', u'type': u'string'},
					 {u'name': u'CO9', u'type': u'string'},
					 {u'name': u'RELEASE', u'type': [u'string', u'null']},
					 {u'name': u'appversion', u'type': u'string'},
					 {u'name': u'brands', u'type': u'string'},
					 {u'name': u'city', u'type': [u'string', u'null']},
					 {u'name': u'deviceType', u'type': u'string'},
					 {u'name': u'devicesinfoExt', u'type': u'string'},
					 {u'name': u'id', u'type': u'int'},
					 {u'name': u'imei', u'type': u'string'},
					 {u'name': u'imsi', u'type': u'string'},
					 {u'name': u'ip', u'type': [u'string', u'null']},
					 {u'name': u'is_push', u'type': u'int'},
					 {u'name': u'istest_device', u'type': u'int'},
					 {u'name': u'language', u'type': [u'string', u'null']},
					 {u'name': u'last_checktime', u'type': [u'float', u'null']},
					 {u'name': u'mac', u'type': [u'string', u'null']},
					 {u'name': u'maingid', u'type': u'string'},
					 {u'name': u'mid', u'type': [u'string', u'null']},
					 {u'name': u'networkType', u'type': u'string'},
					 {u'name': u'now_version', u'type': [u'string', u'null']},
					 {u'name': u'oem', u'type': [u'string', u'null']},
					 {u'name': u'operator', u'type': [u'string', u'null']},
					 {u'name': u'origin_version', u'type': [u'string', u'null']},
					 {u'name': u'plat', u'type': u'string'},
					 {u'name': u'platform', u'type': u'string'},
					 {u'name': u'product', u'type': [u'string', u'null']},
					 {u'name': u'province', u'type': [u'string', u'null']},
					 {u'name': u'push_time', u'type': [u'float', u'null']},
					 {u'name': u'region', u'type': [u'string', u'null']},
					 {u'name': u'reseles', u'type': u'string'},
					 {u'name': u'resolution', u'type': [u'string', u'null']},
					 {u'name': u'sdkversion', u'type': u'string'},
					 {u'name': u'secondOperator', u'type': u'string'},
					 {u'name': u'secondgid', u'type': u'string'},
					 {u'name': u'sim', u'type': [u'string', u'null']},
					 {u'name': u'sn', u'type': [u'string', u'null']},
					 {u'name': u'status', u'type': u'string'},
					 {u'name': u'version', u'type': u'string'},
					 {u'name': u'data_version', u'type': u'string'},
					 {u'name': u'cityCode', u'type': [u'string', u'null']},
					 {u'name': u'provinceCode', u'type': [u'string', u'null']},
					 {u'name': u'up_time', u'type': [u'float', u'null']}], u'type': u'record', u'name': u'DeviceInfo'}
