#!/usr/anaconda2/bin/python
# -*- coding: utf-8 -*-

allFota5DeviceTable = ['deviceInfo201601','deviceInfo201602','deviceInfo201603','deviceInfo201604','deviceInfo201605','deviceInfo201606','deviceInfo201607','deviceInfo201608','deviceInfo201609','deviceInfo201610','deviceInfo201611','deviceInfo201612','deviceInfo201701','deviceInfo201702','deviceInfo201703','deviceInfo201704','deviceInfo201705','deviceInfo201706','deviceInfo201707','deviceInfo201708','deviceInfo201709','deviceInfo201710','deviceInfo201711','deviceInfo201712','deviceInfoother']
allFota5RegionTable = ['regionother','region201701','region201702','region201703','region201704','region201705','region201706','region201707','region201708','region201709','region201710','region201711','region201712','region201612','region201611','region201610','region201609','region201608','region201607','region201606','region201605','region201604','region201603','region201602','region201601']

v5DeviceNeedFields ="*,'5.0' as data_version"
fota5Schema = {u'fields': [{u'name': u'APNType', u'type': [u'string', u'null']},
					 {u'name': u'CO1', u'type': u'string'},
					 {u'name': u'rebootSign', u'type': u'string'},
					 {u'name': u'selfSign', u'type': u'string'},
					 {u'name': u'rebootAppVersion', u'type': u'string'},
					 {u'name': u'CO2', u'type': u'string'},
					 {u'name': u'CO3', u'type': u'string'},
					 {u'name': u'CO4', u'type': u'string'},
					 {u'name': u'CO5', u'type': u'string'},
					 {u'name': u'CO6', u'type': u'string'},
					 {u'name': u'CO7', u'type': u'string'},
					 {u'name': u'CO8', u'type': u'string'},
					 {u'name': u'CO9', u'type': u'string'},
					 {u'name': u'RELEASE', u'type': [u'string', u'null']},
					 {u'name': u'appversion', u'type': u'string'},
					 {u'name': u'brands', u'type': u'string'},
					 {u'name': u'city', u'type': [u'string', u'null']},
					 {u'name': u'deviceType', u'type': u'string'},
					 {u'name': u'devicesinfoExt', u'type': u'string'},
					 {u'name': u'id', u'type': u'int'},
					 {u'name': u'imei', u'type': u'string'},
					 {u'name': u'imsi', u'type': u'string'},
					 {u'name': u'ip', u'type': [u'string', u'null']},
					 {u'name': u'is_push', u'type': u'int'},
					 {u'name': u'istest_device', u'type': u'int'},
					 {u'name': u'language', u'type': [u'string', u'null']},
					 {u'name': u'last_checktime', u'type': [u'float', u'null']},
					 {u'name': u'mac', u'type': [u'string', u'null']},
					 {u'name': u'maingid', u'type': u'string'},
					 {u'name': u'mid', u'type': [u'string', u'null']},
					 {u'name': u'networkType', u'type': u'string'},
					 {u'name': u'now_version', u'type': [u'string', u'null']},
					 {u'name': u'oem', u'type': [u'string', u'null']},
					 {u'name': u'operator', u'type': [u'string', u'null']},
					 {u'name': u'origin_version', u'type': [u'string', u'null']},
					 {u'name': u'plat', u'type': u'string'},
					 {u'name': u'platform', u'type': u'string'},
					 {u'name': u'product', u'type': [u'string', u'null']},
					 {u'name': u'province', u'type': [u'string', u'null']},
					 {u'name': u'push_time', u'type': [u'string', u'null']},
					 {u'name': u'region', u'type': [u'string', u'null']},
					 {u'name': u'reseles', u'type': u'string'},
					 {u'name': u'resolution', u'type': [u'string', u'null']},
					 {u'name': u'sdkversion', u'type': u'string'},
					 {u'name': u'secondOperator', u'type': u'string'},
					 {u'name': u'secondgid', u'type': u'string'},
					 {u'name': u'sim', u'type': [u'string', u'null']},
					 {u'name': u'sn', u'type': [u'string', u'null']},
					 {u'name': u'status', u'type': u'string'},
					 {u'name': u'version', u'type': u'string'},
					 {u'name': u'data_version', u'type': u'string'},
					 {u'name': u'cityCode', u'type': [u'string', u'null']},
					 {u'name': u'provinceCode', u'type': [u'string', u'null']},
					 {u'name': u'up_time', u'type': [u'float', u'null']}], u'type': u'record', u'name': u'DeviceInfo'}
