#!/usr/anaconda2/bin/python
# -*- coding: utf-8 -*-
from datetime import date,timedelta
################################# Fota3 Info #################################################
allFota3DeviceTable = ['devicenew201407','devicenew201408','devicenew201409','devicenew201410','devicenew201411','devicenew201412','devicenew201501','devicenew201502','devicenew201503','devicenew201504','devicenew201505','devicenew201506','devicenew201507','devicenew201508','devicenew201510','devicenew201511','devicenew201512','devicenew201601','devicenew201602','devicenew201603','devicenew201604','devicenew201605','devicenew201606','devicenew201607','devicenew201608','devicenew201609','devicenew201610','devicenew201611','devicenew201612','devicenew201701','devicenew201702','devicenew201703','devicenew201704','devicenew201705','devicenew201706','devicenew201707','devicenew201708','devicenew201709','devicenew201710','devicenew201711','devicenew201712','devicenewother']

allFota3RegionTable = ['region']


v3DeviceNeedFields ="*,'0' as maingid,'0' as secondgid,'0' as secondOperator,'0' as networkType,'0' as CO1,'0' as CO2,'0' as CO3,'0' as CO4,'0' as CO5,'0' as CO6,'0' as CO7,'0' as CO8,'0' as CO9,'0' as CO10,'0' as CO11,'0' as CO12,'3.0' as data_version"
fota3Schema = {u'fields': [{u'name': u'APNType', u'type': [u'string', u'null']},
					 {u'name': u'CO1', u'type': u'string'},
					 {u'name': u'CO10', u'type': u'string'},
					 {u'name': u'CO11', u'type': u'string'},
					 {u'name': u'CO12', u'type': u'string'},
					 {u'name': u'CO2', u'type': u'string'},
					 {u'name': u'CO3', u'type': u'string'},
					 {u'name': u'CO4', u'type': u'string'},
					 {u'name': u'CO5', u'type': u'string'},
					 {u'name': u'CO6', u'type': u'string'},
					 {u'name': u'CO7', u'type': u'string'},
					 {u'name': u'CO8', u'type': u'string'},
					 {u'name': u'CO9', u'type': u'string'},
					 {u'name': u'RELEASE', u'type': [u'string', u'null']},
					 {u'name': u'appversion', u'type': u'string'},
					 {u'name': u'brands', u'type': u'string'},
					 {u'name': u'city', u'type': [u'string', u'null']},
					 {u'name': u'deviceType', u'type': u'string'},
					 {u'name': u'devicesinfoExt', u'type': u'string'},
					 {u'name': u'id', u'type': u'int'},
					 {u'name': u'imei', u'type': u'string'},
					 {u'name': u'imsi', u'type': u'string'},
					 {u'name': u'ip', u'type': [u'string', u'null']},
					 {u'name': u'is_push', u'type': u'int'},
					 {u'name': u'istest_device', u'type': u'int'},
					 {u'name': u'language', u'type': [u'string', u'null']},
					 {u'name': u'last_checktime', u'type': [u'float', u'null']},
					 {u'name': u'mac', u'type': [u'string', u'null']},
					 {u'name': u'maingid', u'type': u'string'},
					 {u'name': u'mid', u'type': [u'string', u'null']},
					 {u'name': u'networkType', u'type': u'string'},
					 {u'name': u'now_version', u'type': [u'string', u'null']},
					 {u'name': u'oem', u'type': [u'string', u'null']},
					 {u'name': u'operator', u'type': [u'string', u'null']},
					 {u'name': u'origin_version', u'type': [u'string', u'null']},
					 {u'name': u'plat', u'type': u'string'},
					 {u'name': u'platform', u'type': u'string'},
					 {u'name': u'product', u'type': [u'string', u'null']},
					 {u'name': u'province', u'type': [u'string', u'null']},
					 {u'name': u'push_time', u'type': [u'float', u'null']},
					 {u'name': u'region', u'type': [u'string', u'null']},
					 {u'name': u'reseles', u'type': u'string'},
					 {u'name': u'resolution', u'type': [u'string', u'null']},
					 {u'name': u'sdkversion', u'type': u'string'},
					 {u'name': u'secondOperator', u'type': u'string'},
					 {u'name': u'secondgid', u'type': u'string'},
					 {u'name': u'sim', u'type': [u'string', u'null']},
					 {u'name': u'sn', u'type': [u'string', u'null']},
					 {u'name': u'status', u'type': u'string'},
					 {u'name': u'version', u'type': u'string'},
					 {u'name': u'data_version', u'type': u'string'},
					 {u'name': u'cityCode', u'type': [u'string', u'null']},
					 {u'name': u'provinceCode', u'type': [u'string', u'null']},
					 {u'name': u'up_time', u'type': [u'float', u'null']}], u'type': u'record', u'name': u'DeviceInfo'}

######################Fota4###############################################
allFota4RegionTable = ['region']
openDeviceNeedFields = "*,'0' as maingid,'0' as secondgid,'0' as secondOperator,'0' as networkType,'0' as sim1_spn,'0' as sim2_spn,'0' as sim2_imsi,'0' as imei2,'0' as esn,'0' as gcmid,'0' as CO7,'0' as CO8,'0' as CO9,if(country_en = 'China','0','1') as country_type,'0' as CO10,'0' as CO11,'0' as CO12,'3' as data_version"

deviceopenschema = {u'fields': [
		{u'name': u'maingid', u'type': u'string'},
		{u'name': u'secondgid', u'type': u'string'},
		{u'name': u'secondOperator', u'type': u'string'},
		 {u'name': u'networkType', u'type': u'string'},
		 {u'name': u'sim1_spn', u'type': u'string'},
		 {u'name': u'sim2_spn', u'type': u'string'},
		 {u'name': u'sim2_imsi', u'type': u'string'},
		 {u'name': u'imei2', u'type': u'string'},
		 {u'name': u'esn', u'type': u'string'},
		 {u'name': u'gcmid', u'type': u'string'},
		 {u'name': u'CO7', u'type': u'string'},
		{u'name': u'CO8', u'type': u'string'},
		 {u'name': u'CO9', u'type': u'string'},
		 {u'name': u'CO10', u'type': u'string'},
		{u'name': u'CO11', u'type': u'string'},
		 {u'name': u'CO12', u'type': u'string'},
		 {u'name': u'country_type', u'type': [u'string', u'null']},
		{u'name': u'APNType', u'type': [u'string', u'null']},
		 {u'name': u'RELEASE', u'type': [u'string', u'null']},
		 {u'name': u'appversion', u'type': u'string'},
		 {u'name': u'brands', u'type': u'string'},
		 {u'name': u'city', u'type': [u'string', u'null']},
		 {u'name': u'deviceType', u'type': u'string'},
		 {u'name': u'devicesinfoExt', u'type': u'string'},
		 {u'name': u'id', u'type': u'int'},
		 {u'name': u'imei', u'type': u'string'},
		 {u'name': u'imsi', u'type': u'string'},
		 {u'name': u'ip', u'type': [u'string', u'null']},
		 {u'name': u'is_push', u'type': u'int'},
		 {u'name': u'istest_device', u'type': u'int'},
		 {u'name': u'language', u'type': [u'string', u'null']},
		 {u'name': u'last_checktime', u'type': [u'float', u'null']},
		 {u'name': u'mac', u'type': [u'string', u'null']},
		 {u'name': u'mid', u'type': [u'string', u'null']},
		 {u'name': u'now_version', u'type': [u'string', u'null']},
		 {u'name': u'oem', u'type': [u'string', u'null']},
		 {u'name': u'operator', u'type': [u'string', u'null']},
		 {u'name': u'origin_version', u'type': [u'string', u'null']},
		 {u'name': u'plat', u'type': u'string'},
		 {u'name': u'platform', u'type': u'string'},
		 {u'name': u'product', u'type': [u'string', u'null']},
		 {u'name': u'province', u'type': [u'string', u'null']},
		 {u'name': u'push_time', u'type': [u'float', u'null']},
		 {u'name': u'region', u'type': [u'string', u'null']},
		 {u'name': u'reseles', u'type': u'string'},
		 {u'name': u'resolution', u'type': [u'string', u'null']},
		 {u'name': u'sdkversion', u'type': u'string'},
		 {u'name': u'sim', u'type': [u'string', u'null']},
		 {u'name': u'sn', u'type': [u'string', u'null']},
		 {u'name': u'status', u'type': u'string'},
		 {u'name': u'version', u'type': u'string'},
		 {u'name': u'data_version', u'type': u'string'},
		 {u'name': u'cityCode', u'type': [u'string', u'null']},
		 {u'name': u'provinceCode', u'type': [u'string', u'null']},
		 {u'name': u'continent_en', u'type': [u'string', u'null']},
		 {u'name': u'COL4', u'type': [u'string', u'null']},
		 {u'name': u'country_en', u'type': [u'string', u'null']},
		 {u'name': u'COL5', u'type': [u'string', u'null']},
		 {u'name': u'COl2', u'type': [u'string', u'null']},
		 {u'name': u'country_zh', u'type': [u'string', u'null']},
		 {u'name': u'province_zh', u'type': [u'string', u'null']},
		 {u'name': u'COL3', u'type': [u'string', u'null']},
		 {u'name': u'city_zh', u'type': [u'string', u'null']},
		 {u'name': u'province_en', u'type': [u'string', u'null']},
		 {u'name': u'ctiy_en', u'type': [u'string', u'null']},
		 {u'name': u'continent_zh', u'type': [u'string', u'null']},
		 {u'name': u'up_time', u'type': [u'float', u'null']}], u'type': u'record', u'name': u'DeviceInfo'}
oldv4DeviceNeedFields ="*,'0' as maingid,'0' as secondgid,'0' as secondOperator,'0' as networkType,'0' as CO1,'0' as CO2,'0' as CO3,'0' as CO4,'0' as CO5,'0' as CO6,'0' as CO7,'0' as CO8,'0' as CO9,'0' as CO10,'0' as CO11,'0' as CO12,'4.0' as data_version"
oldv4deviceschema = {u'fields': [
			{u'name': u'CO1', u'type': u'string'},
			 {u'name': u'CO10', u'type': u'string'},
			 {u'name': u'CO11', u'type': u'string'},
			 {u'name': u'CO12', u'type': u'string'},
			 {u'name': u'CO2', u'type': u'string'},
			 {u'name': u'CO3', u'type': u'string'},
			 {u'name': u'CO4', u'type': u'string'},
			 {u'name': u'CO5', u'type': u'string'},
			 {u'name': u'CO6', u'type': u'string'},
			 {u'name': u'CO7', u'type': u'string'},
			 {u'name': u'CO8', u'type': u'string'},
			 {u'name': u'CO9', u'type': u'string'},
			{u'name': u'maingid', u'type': u'string'},
			 {u'name': u'secondgid', u'type': u'string'},
			 {u'name': u'secondOperator', u'type': u'string'},
			 {u'name': u'networkType', u'type': u'string'},
			{u'name': u'APNType', u'type': [u'string', u'null']},
			 {u'name': u'RELEASE', u'type': [u'string', u'null']},
			 {u'name': u'appversion', u'type': u'string'},
			 {u'name': u'brands', u'type': u'string'},
			 {u'name': u'city', u'type': [u'string', u'null']},
			 {u'name': u'deviceType', u'type': u'string'},
			 {u'name': u'devicesinfoExt', u'type': u'string'},
			 {u'name': u'id', u'type': u'int'},
			 {u'name': u'imei', u'type': u'string'},
			 {u'name': u'imsi', u'type': u'string'},
			 {u'name': u'ip', u'type': [u'string', u'null']},
			 {u'name': u'is_push', u'type': u'int'},
			 {u'name': u'istest_device', u'type': u'int'},
			 {u'name': u'language', u'type': [u'string', u'null']},
			 {u'name': u'last_checktime', u'type': [u'float', u'null']},
			 {u'name': u'mac', u'type': [u'string', u'null']},
			 {u'name': u'mid', u'type': [u'string', u'null']},
			 {u'name': u'now_version', u'type': [u'string', u'null']},
			 {u'name': u'oem', u'type': [u'string', u'null']},
			 {u'name': u'operator', u'type': [u'string', u'null']},
			 {u'name': u'origin_version', u'type': [u'string', u'null']},
			 {u'name': u'plat', u'type': u'string'},
			 {u'name': u'platform', u'type': u'string'},
			 {u'name': u'product', u'type': [u'string', u'null']},
			 {u'name': u'province', u'type': [u'string', u'null']},
			 {u'name': u'push_time', u'type': [u'string', u'null']},
			 {u'name': u'region', u'type': [u'string', u'null']},
			 {u'name': u'reseles', u'type': u'string'},
			 {u'name': u'resolution', u'type': [u'string', u'null']},
			 {u'name': u'sdkversion', u'type': u'string'},
			 {u'name': u'sim', u'type': [u'string', u'null']},
			 {u'name': u'sn', u'type': [u'string', u'null']},
			 {u'name': u'status', u'type': u'string'},
			 {u'name': u'version', u'type': u'string'},
			 {u'name': u'data_version', u'type': u'string'},
			 {u'name': u'cityCode', u'type': [u'string', u'null']},
			 {u'name': u'provinceCode', u'type': [u'string', u'null']},
			 {u'name': u'up_time', u'type': [u'float', u'null']}], u'type': u'record', u'name': u'OldDeviceInfo'}
v4DeviceNeedFields ="*,'4.0' as data_version"
fota4Schema = {u'fields': [{u'name': u'APNType', u'type': [u'string', u'null']},
					 {u'name': u'CO1', u'type': u'string'},
					 {u'name': u'CO10', u'type': u'string'},
					 {u'name': u'CO11', u'type': u'string'},
					 {u'name': u'CO12', u'type': u'string'},
					 {u'name': u'CO2', u'type': u'string'},
					 {u'name': u'CO3', u'type': u'string'},
					 {u'name': u'CO4', u'type': u'string'},
					 {u'name': u'CO5', u'type': u'string'},
					 {u'name': u'CO6', u'type': u'string'},
					 {u'name': u'CO7', u'type': u'string'},
					 {u'name': u'CO8', u'type': u'string'},
					 {u'name': u'CO9', u'type': u'string'},
					 {u'name': u'RELEASE', u'type': [u'string', u'null']},
					 {u'name': u'appversion', u'type': u'string'},
					 {u'name': u'brands', u'type': u'string'},
					 {u'name': u'city', u'type': [u'string', u'null']},
					 {u'name': u'deviceType', u'type': u'string'},
					 {u'name': u'devicesinfoExt', u'type': u'string'},
					 {u'name': u'id', u'type': u'int'},
					 {u'name': u'imei', u'type': u'string'},
					 {u'name': u'imsi', u'type': u'string'},
					 {u'name': u'ip', u'type': [u'string', u'null']},
					 {u'name': u'is_push', u'type': u'int'},
					 {u'name': u'istest_device', u'type': u'int'},
					 {u'name': u'language', u'type': [u'string', u'null']},
					 {u'name': u'last_checktime', u'type': [u'float', u'null']},
					 {u'name': u'mac', u'type': [u'string', u'null']},
					 {u'name': u'maingid', u'type': u'string'},
					 {u'name': u'mid', u'type': [u'string', u'null']},
					 {u'name': u'networkType', u'type': u'string'},
					 {u'name': u'now_version', u'type': [u'string', u'null']},
					 {u'name': u'oem', u'type': [u'string', u'null']},
					 {u'name': u'operator', u'type': [u'string', u'null']},
					 {u'name': u'origin_version', u'type': [u'string', u'null']},
					 {u'name': u'plat', u'type': u'string'},
					 {u'name': u'platform', u'type': u'string'},
					 {u'name': u'product', u'type': [u'string', u'null']},
					 {u'name': u'province', u'type': [u'string', u'null']},
					 {u'name': u'push_time', u'type': [u'string', u'null']},
					 {u'name': u'region', u'type': [u'string', u'null']},
					 {u'name': u'reseles', u'type': u'string'},
					 {u'name': u'resolution', u'type': [u'string', u'null']},
					 {u'name': u'sdkversion', u'type': u'string'},
					 {u'name': u'secondOperator', u'type': u'string'},
					 {u'name': u'secondgid', u'type': u'string'},
					 {u'name': u'sim', u'type': [u'string', u'null']},
					 {u'name': u'sn', u'type': [u'string', u'null']},
					 {u'name': u'status', u'type': u'string'},
					 {u'name': u'version', u'type': u'string'},
					 {u'name': u'data_version', u'type': u'string'},
					 {u'name': u'cityCode', u'type': [u'string', u'null']},
					 {u'name': u'provinceCode', u'type': [u'string', u'null']},
					 {u'name': u'up_time', u'type': [u'float', u'null']}], u'type': u'record', u'name': u'DeviceInfo'}
allFota4TableNames = ['deviceInfo201507',
				 'deviceInfo201508',
				 'deviceInfo201509',
				 'deviceInfo201510',
				 'deviceInfo201511',
				 'deviceInfo201512',
				 'deviceInfo201601',
				 'deviceInfo201602',
				 'deviceInfo201603',
				 'deviceInfo201604',
				 'deviceInfo20160408',
				 'deviceInfo201605',
				 'deviceInfo201606',
				 'deviceInfo201701',
				 'deviceInfo201702',
				 'deviceInfo201703',
				 'deviceInfo201704',
				 'deviceInfo201705',
				 'deviceInfo201706',
				 'deviceInfo201707',
				 'deviceInfo201708',
				 'deviceInfo201709',
				 'deviceInfo201710',
				 'deviceInfo201711',
				 'deviceInfo201712']

######################Fota5###############################################
allFota5DeviceTable = ['deviceInfo201601','deviceInfo201602','deviceInfo201603','deviceInfo201604','deviceInfo201605','deviceInfo201606','deviceInfo201607','deviceInfo201608','deviceInfo201609','deviceInfo201610','deviceInfo201611','deviceInfo201612','deviceInfo201701','deviceInfo201702','deviceInfo201703','deviceInfo201704','deviceInfo201705','deviceInfo201706','deviceInfo201707','deviceInfo201708','deviceInfo201709','deviceInfo201710','deviceInfo201711','deviceInfo201712','deviceInfoother']
allFota5RegionTable = ['regionother','region201701','region201702','region201703','region201704','region201705','region201706','region201707','region201708','region201709','region201710','region201711','region201712','region201612','region201611','region201610','region201609','region201608','region201607','region201606','region201605','region201604','region201603','region201602','region201601']

v5DeviceNeedFields ="*,'5.0' as data_version"
fota5Schema = {u'fields': [{u'name': u'APNType', u'type': [u'string', u'null']},
					 {u'name': u'CO1', u'type': u'string'},
					 {u'name': u'rebootSign', u'type': u'string'},
					 {u'name': u'selfSign', u'type': u'string'},
					 {u'name': u'rebootAppVersion', u'type': u'string'},
					 {u'name': u'CO2', u'type': u'string'},
					 {u'name': u'CO3', u'type': u'string'},
					 {u'name': u'CO4', u'type': u'string'},
					 {u'name': u'CO5', u'type': u'string'},
					 {u'name': u'CO6', u'type': u'string'},
					 {u'name': u'CO7', u'type': u'string'},
					 {u'name': u'CO8', u'type': u'string'},
					 {u'name': u'CO9', u'type': u'string'},
					 {u'name': u'RELEASE', u'type': [u'string', u'null']},
					 {u'name': u'appversion', u'type': u'string'},
					 {u'name': u'brands', u'type': u'string'},
					 {u'name': u'city', u'type': [u'string', u'null']},
					 {u'name': u'deviceType', u'type': u'string'},
					 {u'name': u'devicesinfoExt', u'type': u'string'},
					 {u'name': u'id', u'type': u'int'},
					 {u'name': u'imei', u'type': u'string'},
					 {u'name': u'imsi', u'type': u'string'},
					 {u'name': u'ip', u'type': [u'string', u'null']},
					 {u'name': u'is_push', u'type': u'int'},
					 {u'name': u'istest_device', u'type': u'int'},
					 {u'name': u'language', u'type': [u'string', u'null']},
					 {u'name': u'last_checktime', u'type': [u'float', u'null']},
					 {u'name': u'mac', u'type': [u'string', u'null']},
					 {u'name': u'maingid', u'type': u'string'},
					 {u'name': u'mid', u'type': [u'string', u'null']},
					 {u'name': u'networkType', u'type': u'string'},
					 {u'name': u'now_version', u'type': [u'string', u'null']},
					 {u'name': u'oem', u'type': [u'string', u'null']},
					 {u'name': u'operator', u'type': [u'string', u'null']},
					 {u'name': u'origin_version', u'type': [u'string', u'null']},
					 {u'name': u'plat', u'type': u'string'},
					 {u'name': u'platform', u'type': u'string'},
					 {u'name': u'product', u'type': [u'string', u'null']},
					 {u'name': u'province', u'type': [u'string', u'null']},
					 {u'name': u'push_time', u'type': [u'string', u'null']},
					 {u'name': u'region', u'type': [u'string', u'null']},
					 {u'name': u'reseles', u'type': u'string'},
					 {u'name': u'resolution', u'type': [u'string', u'null']},
					 {u'name': u'sdkversion', u'type': u'string'},
					 {u'name': u'secondOperator', u'type': u'string'},
					 {u'name': u'secondgid', u'type': u'string'},
					 {u'name': u'sim', u'type': [u'string', u'null']},
					 {u'name': u'sn', u'type': [u'string', u'null']},
					 {u'name': u'status', u'type': u'string'},
					 {u'name': u'version', u'type': u'string'},
					 {u'name': u'data_version', u'type': u'string'},
					 {u'name': u'cityCode', u'type': [u'string', u'null']},
					 {u'name': u'provinceCode', u'type': [u'string', u'null']},
					 {u'name': u'up_time', u'type': [u'float', u'null']}], u'type': u'record', u'name': u'DeviceInfo'}
######################### SPARK ########################################################################################
sparkJobCMD = 'export SPARK_CLASSPATH=/home/ct_fota/YangShuxuan/OptFotaSalesCount/customSparkJarYSX/conf && \
		spark-submit   --class "wuxi99.CtFotaSalesApp"  --packages com.databricks:spark-avro_2.10:2.0.1,org.clapper:grizzled-slf4j_2.11:1.3.0 \
		/home/ct_fota/YangShuxuan/OptFotaSalesCount/customSparkJarYSX/ctfota_2.10-0.9.6.jar %s' %((date.today()-timedelta(1)).strftime('%Y-%m-%d'),)
	